spring.application.name=Task_Tracker_App
server.port=8088
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.database.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=Abhipostgre@2004


spring.jpa.hibernate.ddl-auto=update